// orders.js
// Realistic sample orders dataset (static, but structured like real inventory/order data)

const Orders = [
  {
    orderId: "SO-2025-1201",
    orderDate: "2025-12-01",
    productName: "Foldable Mini Drone",
    ProductNumber: "84512",
    sku: "DRN-FOLD-01",
    category: "Drones",
    customer: "Jimmy Tan",
    channel: "Online",
    warehouse: "SG-WH1",
    qty: 2,
    unitPrice: 149.0,
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    orderId: "SO-2025-1202",
    orderDate: "2025-12-02",
    productName: "AIRSHOT GT102 Drone",
    ProductNumber: "98373",
    sku: "DRN-AIR-102",
    category: "Drones",
    customer: "Nur Aisyah",
    channel: "Online",
    warehouse: "SG-WH2",
    qty: 1,
    unitPrice: 399.0,
    paymentStatus: "Refunded",
    shipping: "Declined",
  },
  {
    orderId: "SO-2025-1203",
    orderDate: "2025-12-02",
    productName: "Ruka F11 Pro Drone",
    ProductNumber: "44031",
    sku: "DRN-RUKA-F11",
    category: "Drones",
    customer: "Ethan Lim",
    channel: "Retail",
    warehouse: "SG-WH1",
    qty: 1,
    unitPrice: 529.0,
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    orderId: "SO-2025-1204",
    orderDate: "2025-12-03",
    productName: "Camera Drone",
    ProductNumber: "58932",
    sku: "DRN-CAM-4K",
    category: "Drones",
    customer: "Lawrence Ng",
    channel: "Online",
    warehouse: "SG-WH2",
    qty: 1,
    unitPrice: 279.0,
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    orderId: "SO-2025-1205",
    orderDate: "2025-12-03",
    productName: "Speed KH995 Drone",
    ProductNumber: "34522",
    sku: "DRN-KH995",
    category: "Drones",
    customer: "Chloe Goh",
    channel: "Distributor",
    warehouse: "SG-WH3",
    qty: 4,
    unitPrice: 119.0,
    paymentStatus: "Due",
    shipping: "Processing",
  },
  {
    orderId: "SO-2025-1206",
    orderDate: "2025-12-04",
    productName: "GPS 4K Drone",
    ProductNumber: "19048",
    sku: "DRN-GPS-4K",
    category: "Drones",
    customer: "Haziq Rahman",
    channel: "Online",
    warehouse: "SG-WH1",
    qty: 2,
    unitPrice: 449.0,
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    orderId: "SO-2025-1207",
    orderDate: "2025-12-04",
    productName: "Drone Propellers (Spare Set)",
    ProductNumber: "92347",
    sku: "ACC-PROP-SET",
    category: "Accessories",
    customer: "Janice Siew",
    channel: "Online",
    warehouse: "SG-WH2",
    qty: 3,
    unitPrice: 18.9,
    paymentStatus: "Refunded",
    shipping: "Declined",
  },

  // ---- More realistic variety (mix of status/payment/date/qty) ----
  {
    orderId: "SO-2025-1208",
    orderDate: "2025-12-05",
    productName: "Drone Battery Pack (2x)",
    ProductNumber: "61104",
    sku: "ACC-BATT-2P",
    category: "Accessories",
    customer: "Shawn Teo",
    channel: "Retail",
    warehouse: "SG-WH1",
    qty: 2,
    unitPrice: 39.9,
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    orderId: "SO-2025-1209",
    orderDate: "2025-12-05",
    productName: "Controller Grip Kit",
    ProductNumber: "77192",
    sku: "ACC-GRIP-KIT",
    category: "Accessories",
    customer: "Alicia Ho",
    channel: "Online",
    warehouse: "SG-WH2",
    qty: 1,
    unitPrice: 14.9,
    paymentStatus: "Paid",
    shipping: "Processing",
  },
  {
    orderId: "SO-2025-1210",
    orderDate: "2025-12-06",
    productName: "FPV Goggles Lite",
    ProductNumber: "50811",
    sku: "FPV-GOG-LITE",
    category: "FPV",
    customer: "Wei Ming",
    channel: "Online",
    warehouse: "SG-WH3",
    qty: 1,
    unitPrice: 189.0,
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    orderId: "SO-2025-1211",
    orderDate: "2025-12-06",
    productName: "Landing Pad (Foldable)",
    ProductNumber: "30219",
    sku: "ACC-LPAD-FLD",
    category: "Accessories",
    customer: "Farah N.",
    channel: "Distributor",
    warehouse: "SG-WH3",
    qty: 10,
    unitPrice: 9.5,
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    orderId: "SO-2025-1212",
    orderDate: "2025-12-07",
    productName: "Mini Drone Carry Case",
    ProductNumber: "44710",
    sku: "ACC-CASE-MINI",
    category: "Accessories",
    customer: "Dylan Koh",
    channel: "Online",
    warehouse: "SG-WH2",
    qty: 2,
    unitPrice: 24.9,
    paymentStatus: "Paid",
    shipping: "Processing",
  },
  {
    orderId: "SO-2025-1213",
    orderDate: "2025-12-08",
    productName: "AIRSHOT GT102 Prop Guard",
    ProductNumber: "98374",
    sku: "ACC-GT102-GRD",
    category: "Accessories",
    customer: "Mei Ling",
    channel: "Retail",
    warehouse: "SG-WH1",
    qty: 5,
    unitPrice: 7.9,
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    orderId: "SO-2025-1214",
    orderDate: "2025-12-09",
    productName: "GPS 4K Drone (Bundle)",
    ProductNumber: "19049",
    sku: "DRN-GPS-4K-B",
    category: "Drones",
    customer: "Karthik S.",
    channel: "Online",
    warehouse: "SG-WH1",
    qty: 1,
    unitPrice: 499.0,
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    orderId: "SO-2025-1215",
    orderDate: "2025-12-10",
    productName: "Drone Motor Replacement (Pair)",
    ProductNumber: "61290",
    sku: "ACC-MOTOR-PR",
    category: "Accessories",
    customer: "Nurul I.",
    channel: "Distributor",
    warehouse: "SG-WH3",
    qty: 6,
    unitPrice: 29.0,
    paymentStatus: "Paid",
    shipping: "Processing",
  },
  {
    orderId: "SO-2025-1216",
    orderDate: "2025-12-11",
    productName: "Camera Drone ND Filter Set",
    ProductNumber: "78441",
    sku: "ACC-ND-SET",
    category: "Accessories",
    customer: "Zack Lee",
    channel: "Online",
    warehouse: "SG-WH2",
    qty: 1,
    unitPrice: 19.9,
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    orderId: "SO-2025-1217",
    orderDate: "2025-12-12",
    productName: "FPV Antenna Upgrade",
    ProductNumber: "29118",
    sku: "FPV-ANT-UP",
    category: "FPV",
    customer: "Siti H.",
    channel: "Retail",
    warehouse: "SG-WH1",
    qty: 3,
    unitPrice: 12.9,
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    orderId: "SO-2025-1218",
    orderDate: "2025-12-13",
    productName: "Foldable Mini Drone (Bulk)",
    ProductNumber: "84513",
    sku: "DRN-FOLD-01B",
    category: "Drones",
    customer: "SkyHobby Pte Ltd",
    channel: "Distributor",
    warehouse: "SG-WH3",
    qty: 20,
    unitPrice: 129.0,
    paymentStatus: "Paid",
    shipping: "Processing",
  },
  {
    orderId: "SO-2025-1219",
    orderDate: "2025-12-14",
    productName: "Drone Charger Hub",
    ProductNumber: "55231",
    sku: "ACC-CHG-HUB",
    category: "Accessories",
    customer: "Grace Ong",
    channel: "Online",
    warehouse: "SG-WH2",
    qty: 2,
    unitPrice: 34.9,
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    orderId: "SO-2025-1220",
    orderDate: "2025-12-15",
    productName: "Speed KH995 Drone",
    ProductNumber: "34523",
    sku: "DRN-KH995-B",
    category: "Drones",
    customer: "Harrison Y.",
    channel: "Retail",
    warehouse: "SG-WH1",
    qty: 2,
    unitPrice: 109.0,
    paymentStatus: "Refunded",
    shipping: "Declined",
  },
];
